#!/usr/bin/env node
/**
 * makeTarballApp.mjs — mirror a `source/` app into the `tarball/` track.
 *
 *   node scripts/makeTarballApp.mjs markets-grid-lab
 *   node scripts/makeTarballApp.mjs --all
 *
 * The two tracks run the SAME app source against different resolution:
 *
 *   source/<app>   Vite through the platform's alias layer, tsc through its
 *                  generated tsconfig.consumer.json
 *   tarball/<app>  plain Vite, plain tsconfig, packages installed from
 *                  vendor/*.tgz — exactly what an external team gets
 *
 * So the app's own `src/` is copied verbatim and only its four config surfaces
 * are rewritten. If a tarball app needs a source edit to build, that is a
 * genuine external-consumption defect in the packages, not a porting problem.
 *
 * Re-running is safe: it regenerates the configs and refreshes src/, preserving
 * nothing app-specific outside the table below.
 */
import {
  cpSync, existsSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync,
} from 'node:fs';
import { join } from 'node:path';
import { REPO_ROOT } from './resolvePlatform.mjs';

const SOURCE_ROOT = join(REPO_ROOT, 'source');
const TARBALL_ROOT = join(REPO_ROOT, 'tarball');
const VENDOR_DIR = join(REPO_ROOT, 'vendor');

/**
 * Per-app config that cannot be inferred from the source tree.
 *
 * Ports are the source port + 1000 so both tracks of the same app can run at
 * once. `open` is deliberately dropped — these are built in CI, not browsed.
 */
const APPS = {
  'basic': { port: 6194 },
  'dataprovider-editor': { port: 6193 },
  'design-system': { port: 6310 },
  'markets-grid-lab': { port: 6300, assetsInclude: ['**/*.md'] },
  'star-demo': { port: 6175, svgr: true },
  'stomp-marketsgrid-minimal': { port: 6213 },
  // stomp-view-server is intentionally absent: it imports zero
  // @wellsfargo-starui packages, so a tarball copy would prove nothing.
};

const SKIP_COPY = new Set(['node_modules', 'dist', '.vite', 'package-lock.json', '.turbo']);

function log(msg) {
  process.stdout.write(`[make-tarball-app] ${msg}\n`);
}

/** Every packed member package, read from what setup.mjs vendored. */
function vendoredPackages() {
  if (!existsSync(VENDOR_DIR)) {
    throw new Error('vendor/ is empty — run `node scripts/setup.mjs` first.');
  }
  return readdirSync(VENDOR_DIR)
    .filter((f) => f.endsWith('.tgz'))
    .map((f) => ({
      name: `@wellsfargo-starui/${f.replace(/^wellsfargo-starui-/, '').replace(/\.tgz$/, '')}`,
      spec: `file:../../vendor/${f}`,
    }))
    .sort((a, b) => a.name.localeCompare(b.name));
}

function viteConfig(app, cfg) {
  const imports = [
    "import { defineConfig } from 'vite';",
    "import react from '@vitejs/plugin-react';",
    ...(cfg.svgr ? ["import svgr from 'vite-plugin-svgr';"] : []),
  ].join('\n');

  const plugins = cfg.svgr ? 'react(), svgr()' : 'react()';
  const extra = cfg.assetsInclude
    ? `\n  assetsInclude: [${cfg.assetsInclude.map((g) => `'${g}'`).join(', ')}],`
    : '';

  return `${imports}

/**
 * TARBALL TRACK — deliberately plain. GENERATED by scripts/makeTarballApp.mjs.
 *
 * No platform imports, no aliases: this app installs @wellsfargo-starui/* as
 * ordinary npm packages, so it is the honest test of the "install the package,
 * import one stylesheet, done" contract. If this file ever needs platform
 * helpers to build, external consumption is broken and the PACKAGES need the
 * fix — not this config.
 *
 * The source-track twin of this app is source/${app}/.
 */
export default defineConfig({
  plugins: [${plugins}],
  server: { port: ${cfg.port} },${extra}
  optimizeDeps: {
    // Vite dev prebundles bare node_modules imports into .vite/deps/, which
    // relocates the module and breaks the SharedWorker's
    // \`new URL(..., import.meta.url)\` resolution. A package cannot opt itself
    // out of the optimizer, so consumers add this one line. \`vite build\` and
    // every other bundler need nothing.
    exclude: ['@wellsfargo-starui/host-data'],
  },
});
`;
}

function tailwindConfig(app) {
  return `/** @type {import('tailwindcss').Config} */
// TARBALL TRACK — GENERATED by scripts/makeTarballApp.mjs.
// The preset comes from the INSTALLED design-system package, not the platform
// repo's scripts/. NOTE it is a NAMED export: the package ships no default, so
// \`import preset from '.../tailwind'\` yields undefined and Tailwind dies with
// "Cannot read properties of undefined (reading 'future')" pointing at an
// unrelated CSS file.
import { tailwindPreset } from '@wellsfargo-starui/design-system/tailwind';

export default {
  presets: [tailwindPreset],
  content: [
    './index.html',
    './src/**/*.{ts,tsx}',
    './node_modules/@wellsfargo-starui/*/dist/**/*.{js,mjs}',
    '../../node_modules/@wellsfargo-starui/*/dist/**/*.{js,mjs}',
  ],
};
`;
}

/** Strip comments so JSONC tsconfigs parse. */
function readJsonc(path) {
  return JSON.parse(readFileSync(path, 'utf8').replace(/^\s*\/\/.*$/gm, ''));
}

function rewriteTsconfig(destDir, filename) {
  const path = join(destDir, filename);
  if (!existsSync(path)) return false;
  const cfg = readJsonc(path);
  // Local base, NOT the platform's tsconfig.consumer.json — that maps
  // @wellsfargo-starui/* onto the platform's packages/ tree, which would defeat
  // the whole point of this track.
  cfg.extends = '../../tsconfig.base.json';
  // `extends` REPLACES compilerOptions.paths rather than merging, and here we
  // want plain node resolution anyway.
  if (cfg.compilerOptions?.paths) delete cfg.compilerOptions.paths;
  writeFileSync(path, `${JSON.stringify(cfg, null, 2)}\n`);
  return true;
}

function makeApp(app) {
  const cfg = APPS[app];
  if (!cfg) throw new Error(`No tarball spec for "${app}". Known: ${Object.keys(APPS).join(', ')}`);

  const srcDir = join(SOURCE_ROOT, app);
  const destDir = join(TARBALL_ROOT, app);
  if (!existsSync(srcDir)) throw new Error(`source/${app} does not exist`);

  // Preserve the installed node_modules so re-running does not force a full
  // reinstall of every app.
  const keptModules = join(destDir, 'node_modules');
  const hadModules = existsSync(keptModules);
  if (existsSync(destDir)) {
    for (const entry of readdirSync(destDir)) {
      if (entry === 'node_modules') continue;
      rmSync(join(destDir, entry), { recursive: true, force: true, maxRetries: 5, retryDelay: 100 });
    }
  }
  mkdirSync(destDir, { recursive: true });

  for (const entry of readdirSync(srcDir)) {
    if (SKIP_COPY.has(entry)) continue;
    cpSync(join(srcDir, entry), join(destDir, entry), { recursive: true });
  }

  // ── package.json ───────────────────────────────────────────────────────
  const pkg = JSON.parse(readFileSync(join(srcDir, 'package.json'), 'utf8'));
  const sourcePort = String(pkg.scripts?.client ?? '').match(/localhost:(\d+)/)?.[1];

  pkg.name = `${pkg.name}-tarball`;
  pkg.description =
    `Tarball-track twin of source/${app}. Consumes @wellsfargo-starui/* as installed `
    + `npm packages (vendor/*.tgz) with a plain Vite config — the path an external team takes.`;

  // Every packed member, not just the direct imports: the tarballs depend on
  // each other by concrete version and none are published, so any transitive
  // one left out sends npm to the registry for a 404.
  const deps = Object.fromEntries(
    Object.entries(pkg.dependencies ?? {}).filter(([k]) => !k.startsWith('@wellsfargo-starui/')),
  );
  for (const { name, spec } of vendoredPackages()) deps[name] = spec;
  pkg.dependencies = Object.fromEntries(Object.entries(deps).sort(([a], [b]) => a.localeCompare(b)));

  // Isolated install — no hoisted root node_modules to borrow React types from.
  const dev = { ...(pkg.devDependencies ?? {}) };
  dev['@types/react'] ??= '19.2.18';
  dev['@types/react-dom'] ??= '19.2.4';
  pkg.devDependencies = Object.fromEntries(Object.entries(dev).sort(([a], [b]) => a.localeCompare(b)));

  // Retarget any script that hardcoded the source port (e.g. star-demo's OpenFin launcher).
  if (sourcePort) {
    for (const [k, v] of Object.entries(pkg.scripts ?? {})) {
      if (typeof v === 'string') pkg.scripts[k] = v.replaceAll(`localhost:${sourcePort}`, `localhost:${cfg.port}`);
    }
  }

  writeFileSync(join(destDir, 'package.json'), `${JSON.stringify(pkg, null, 2)}\n`);

  // ── configs ────────────────────────────────────────────────────────────
  writeFileSync(join(destDir, 'vite.config.ts'), viteConfig(app, cfg));
  if (existsSync(join(destDir, 'tailwind.config.js'))) {
    writeFileSync(join(destDir, 'tailwind.config.js'), tailwindConfig(app));
  }
  const tsconfigs = ['tsconfig.json', 'tsconfig.app.json', 'tsconfig.node.json']
    .filter((f) => rewriteTsconfig(destDir, f));

  log(`${app} -> tarball/${app} (port ${cfg.port}, ${tsconfigs.length} tsconfig(s)${hadModules ? ', kept node_modules' : ''})`);
}

const args = process.argv.slice(2);
const targets = args.includes('--all') ? Object.keys(APPS) : args;

if (targets.length === 0) {
  process.stderr.write(
    `Usage: node scripts/makeTarballApp.mjs <app> | --all\nKnown apps: ${Object.keys(APPS).join(', ')}\n`,
  );
  process.exit(1);
}

for (const app of targets) makeApp(app);
log(`done — ${targets.length} app(s)`);
